# Model dir
MODEL_NAME: test11
CHECKPOINT_DIR: './checkpoints'

# Data
TRAIN_FEATURES: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/features/part0_train.bin'
TRAIN_LABELS: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/labels/part0_train.meta'
VAL_FEATURES: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/features/part1_test.bin'
VAL_LABELS: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/labels/part1_test.meta'
FEATURE_DIM: 256
BATCH_SIZE: 40
SAMPLES_PER_CLASS: 40
MIN_EDGES_PER_CLASS: 0

# Graph
K: 50

# TAU: 0.3
HIDDEN_DIM: 256
OUT_DIM: 256
WINDOW_SIZE: 0

# Training
LR: 0.0002
EPOCHS: 200
WEIGHT_DECAY: 0.00003
DROPOUT: 0.15