# Model dir
MODEL_NAME: bs40000_k60_lr5e-5_ep500_do0.2_030
CHECKPOINT_DIR: './checkpoints'

# Data
TRAIN_FEATURES: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/features/part0_train.bin'
TRAIN_LABELS: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/labels/part0_train.meta'
VAL_FEATURES: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/features/part1_test.bin'
VAL_LABELS: '/home/djordje/Documents/Projects/pyg/learn-to-cluster/data/labels/part1_test.meta'
FEATURE_DIM: 256
BATCH_SIZE: 40000
SAMPLES_PER_CLASS: 40

# Graph
K: 60

# TAU: 0.3
HIDDEN_DIM: 512
OUT_DIM: 256
WINDOW_SIZE: 20

# Training
LR: 0.00005
EPOCHS: 500
WEIGHT_DECAY: 0.
DROPOUT: 0.2